### PR TITLE
moved postgres DB credentials to .env file addressing issue #67

### PR DESCRIPTION
**Pull request by Deekshithrathod**
Address the issue #67 

1. Moved out the sensitive information like DB username & password to a .env file
2. Added a .env.example file to copy the credentials from when setting up locally

Additional Todos,
- [ ] update onboarding documentation asking the user to create a .env file & copying the creds from .env.example

### CODE REVIEW

**Comment by techsavvyash** [comment]
Hey @Deekshithrathod,
Can you fix the GHA script to create a `.env` using the `.env.sample` as well.

**Comment by Deekshithrathod** [comment]
Sure, can do. Will update the PR by EOD

**Comment by Deekshithrathod** [comment]
@techsavvyash Done.
1. Updated GHA to make .env file from .env.example while testing PR
2. How do you want to handle the documentation updation? I mean, do you want to create a separate issue or do you want me to make changes to [01-code-setup.md](https://github.com/ChakshuGautam/cQube-ingestion/blob/master/docs/01-code-setup.md) in this PR itself?

**Comment by Deekshithrathod** [comment]
@techsavvyash Hey, made changes. Feel free to review & let me know if want me to change any commits.

**Comment by techsavvyash** [comment]
Hey @Deekshithrathod,
Have added a .env.sample in https://github.com/ChakshuGautam/cQube-ingestion/pull/101.

Can you update this PR to create a env based on that?

**Comment by Deekshithrathod** [comment]
sure, can do.

**Comment by techsavvyash** [comment]
Hey @Deekshithrathod, thanks for the PR, have merged it.

**Pull request merged**
