### PR TITLE
Moved the docker DB secrets to an env file

### PR DESCRIPTION
**Pull request by Midas847**
Description:
PR to add the code developed as part of C4GT" 23

Changes:
Added the code developed as part of C4GT" 23

todo:
- [x] Make a .env file.
- [x] Create a env variable named as POSTGRES_PASSWORD
- [x] Use that inside of docker-compose.yaml

### CODE REVIEW

**Comment by techsavvyash** [comment]
Hey @Midas847, can you open this PR taking the master as base? Currently you have taken either `refactor` or `jharkhand` as base and hence a lot of unwanted commits are a part of this PR as well.

**Comment by Midas847** [comment]
Hey @techsavvyash , it was previously master, I now changed it to jharkhand. I have no idea how to remove these unnecessary commits.

**Comment by techsavvyash** [comment]
Don't change the branch on the base repo of the PR, keep it as  `ChakshuGautam:master` only, instead make **only** the docker related changes on the `master` branch of your fork and then raise a PR from the `master` branch of your fork to the `master` branch of this repo. Makes sense?

**Review by ChakshuGautam — COMMENTED** [review]
Let's remove package-lock.json, yarn.lock, *.ts. It seems those have been added from a different commit.

**Pull request closed without merging**
